version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network
    links:
      - app

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:7.3-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    links:
      - db

  cli:
    build:
      context: ./docker/php/cli
      dockerfile: Dockerfile
    container_name: cli
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7.24
    container_name: db
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: news
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql/db/:/var/lib/mysql/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
